WITH RECURSIVE GENERATION_CTE AS (
-- 1세대
SELECT ID, 1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
    
UNION ALL

-- 다음 세대
SELECT e.ID, g.GENERATION + 1
FROM ECOLI_DATA e
JOIN GENERATION_CTE g ON e.PARENT_ID = g.ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM GENERATION_CTE
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;