WITH RANKED AS(
    SELECT
        ID,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RK
    FROM ECOLI_DATA   
),
TOTAL AS (
    SELECT COUNT(*) AS CNT
    FROM ECOLI_DATA
)

SELECT
    ID,
    CASE
        WHEN RK <= CNT / 4 THEN 'CRITICAL'
        WHEN RK <= CNT / 2 THEN 'HIGH'
        WHEN RK <= CNT * 3 / 4 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED, TOTAL
ORDER BY ID;